COMPILER=g++
OPTIONS= -W -Wall -O1
CHMOD=chmod 777
Heure_1_A_1:Heure_1_A_1.h Heure_1_A_1.cpp
	${COMPILER} ${OPTIONS} Heure_1_A_1.cpp -o Heure_1_A_1
	${CHMOD} Heure_1_A_1
	./Heure_1_A_1

clean:
	rm -rf *.o